cargo-features = ["panic-immediate-abort"]

[package]
name = "cellboot-avr128da64"
version = "0.1.0"
description = "Bootloader firmware for the CellGuard cellcore (AVR128DA64)."
authors = ["Simon Berger <simon@siku2.io>"]
edition = "2024"
license = "AGPL-3.0-or-later"

[[bin]]
name = "cellboot-avr128da64"
test = false
bench = false

[dependencies]
avr-device = { version = "0.8", features = ["avr128da64", "rt"] }
avrxt-hal = { path = "../libraries/avrxt-hal", features = ["avr128da64"] }
cellboot = { path = "../libraries/cellboot", features = ["avr128", "drivers"] }
cat25 = { path = "../libraries/cat25" }
crc = { path = "../libraries/crc" }
embedded-hal = { version = "1", default-features = false }
embedded-hal-bus = { version = "0.3", default-features = false }
embedded-io = { version = "0.7", default-features = false }
cellguard-panic = { path = "../libraries/cellguard-panic", features = ["hal"] }

[patch.crates-io]
avr-device = { git = "https://github.com/stargrid-systems/avr-device", rev = "73ba68ab5bd7bb03874bc456b329f4c141f1a08e" }

[profile.dev]
panic = "immediate-abort"
lto = true
opt-level = "s"

[profile.release]
panic = "immediate-abort"
codegen-units = 1
debug = true
lto = true
# opt-level "z" measured 582 B smaller than "s" for this binary.
opt-level = "z"
