[workspace]
resolver = "3"
members = [
    "ads131m08",
    "avrxt-hal",
    "cat25",
    "cellagent",
    "cellboot",
    "cellcore",
    "cellcore-runtime",
    "cellguard-protocol",
    "cellprog",
    "crc",
    "panic-log",
    "p3t1755",
    "tca9535",
    "updi",
]

[workspace.package]
authors = ["Simon Berger <simon@siku2.io>"]
edition = "2024"
license = "AGPL-3.0-or-later"
publish = false
repository = "https://github.com/stargrid-systems/cellguard"
rust-version = "1.93"

[workspace.lints.rustdoc]
missing_crate_level_docs = "warn"
unescaped_backticks = "warn"

# See: <https://rust-lang.github.io/rust-clippy/master/index.html>
[workspace.lints.clippy]
# Groups
cargo = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
# Individual lints
allow_attributes = "warn"
allow_attributes_without_reason = "warn"
expect_used = "warn"
float_arithmetic = "warn"
indexing_slicing = "warn"
undocumented_unsafe_blocks = "warn"
unnecessary_safety_comment = "warn"
unnecessary_safety_doc = "warn"
unwrap_used = "warn"

[workspace.dependencies]
avrxt-hal = { path = "avrxt-hal" }
cat25 = { path = "cat25" }
cellagent = { path = "cellagent" }
cellboot = { path = "cellboot" }
cellcore = { path = "cellcore" }
cellguard-protocol = { path = "cellguard-protocol" }
cellprog = { path = "cellprog" }
crc = { path = "crc" }
panic-log = { path = "panic-log" }
updi = { path = "updi" }

avr-device = { version = "0.8", default-features = false }
embedded-hal = { version = "1", default-features = false }
embedded-hal-mock = { version = "0.11", default-features = false }
embedded-io = { version = "0.7", default-features = false }
hmac-sha256 = { version = "1", default-features = false }
ufmt = { version = "0.2", default-features = false }
zerocopy = { version = "0.8", default-features = false }

[patch.crates-io]
avr-device = { git = "https://github.com/stargrid-systems/avr-device", rev = "73ba68ab5bd7bb03874bc456b329f4c141f1a08e" }
