[package]
name = "cellprog"
version = "0.1.0"
description = "Hardware-independent programmer logic for the CellGuard PROG MCU."
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
cellboot.workspace = true
crc.workspace = true
cellguard-protocol = { workspace = true, features = ["bootloader"] }

[lints]
workspace = true
