[package]
name = "cellagent"
version = "0.1.0"
description = "Runtime logic for the CellGuard cellagent balancer MCU."
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
cellguard-protocol.workspace = true
embedded-io.workspace = true
panic-log.workspace = true

[lints]
workspace = true
